name = 'NemaFLPAnalyses'
uuid = 'd13c1f00-513d-422d-a4a6-8042819a2d5d'
description = 'Analyses for solving facility location problems.'
language = 'Julia'
analysis = true
code_dependencies = ["139558ca-173a-4441-81cb-fa3a212d2517"]

[Scripts.final-analysis]
name = "Final analysis"
description = "Final analysis for Outdoor Logistics FLP problem"
path = 'runs/final_analysis.jl'
code_runner = {type = "ExternalCodeRunner", address = "http://google.com/final-analysis"}

[Scripts.paper-example]
name = "Paper example"
description = "Example for the paper describing the FLP methodology."
path = 'runs/paper_example.jl'
code_runner = {type = "ExternalCodeRunner", address = "http://google.com/paper-example"}

[Scripts.manual-plan-development]
name = "Manual plan"
description = "Plan developed based on manual ranking and order of facilities."
path = 'runs/manual_plan.jl'
code_runner = {type = "ExternalCodeRunner", address = "http://google.com/paper-example"}
